"""Offline Zerodha payload parsing and instrument resolution."""

from dhan_lean.providers.zerodha.historical import (
    HistoricalCandleParseError,
    ParsedHistoricalCandles,
    parse_historical_candles,
)
from dhan_lean.providers.zerodha.instruments import (
    AmbiguousInstrumentError,
    InstrumentMasterParseError,
    InstrumentNotFoundError,
    InstrumentResolutionError,
    InstrumentQuery,
    InstrumentRecord,
    InstrumentSnapshot,
    resolve_instrument,
    parse_instrument_snapshot,
)
from dhan_lean.providers.zerodha.broker_protocol import (
    BrokerErrorCode,
    BrokerRequestValidationError,
    BrokerResponse,
    BrokerResponseValidationError,
    CandleRequest,
    ErrorPolicy,
    FramingError,
    HistoricalBroker,
    PROVIDER_ERROR_CODES,
    SessionState,
    TransportStatus,
    ZerodhaBrokerError,
    decode_json_frame,
    decode_request,
    decode_response,
    encode_json_frame,
    encode_request,
    encode_response,
    error_policy,
)
from dhan_lean.providers.zerodha.fake_broker import (
    DeterministicFakeBroker,
    FakeBrokerSequenceExhausted,
    FakeBrokerUnexpectedRequest,
)
from dhan_lean.providers.zerodha.planning import (
    FINGERPRINT_SCHEMA_VERSION,
    PLANNING_SCHEMA_VERSION,
    ZerodhaPlannedRequest,
    ZerodhaPlanningError,
    ZerodhaPlanningInput,
    PlanningErrorCode,
    plan_historical_candles,
)

__all__ = [
    "AmbiguousInstrumentError",
    "HistoricalCandleParseError",
    "InstrumentMasterParseError",
    "InstrumentNotFoundError",
    "InstrumentResolutionError",
    "InstrumentQuery",
    "InstrumentRecord",
    "InstrumentSnapshot",
    "ParsedHistoricalCandles",
    "parse_historical_candles",
    "parse_instrument_snapshot",
    "resolve_instrument",
    "BrokerErrorCode",
    "BrokerRequestValidationError",
    "BrokerResponse",
    "BrokerResponseValidationError",
    "CandleRequest",
    "DeterministicFakeBroker",
    "ErrorPolicy",
    "FakeBrokerSequenceExhausted",
    "FakeBrokerUnexpectedRequest",
    "FramingError",
    "HistoricalBroker",
    "PROVIDER_ERROR_CODES",
    "SessionState",
    "TransportStatus",
    "ZerodhaBrokerError",
    "decode_json_frame",
    "decode_request",
    "decode_response",
    "encode_json_frame",
    "encode_request",
    "encode_response",
    "error_policy",
    "FINGERPRINT_SCHEMA_VERSION",
    "PLANNING_SCHEMA_VERSION",
    "PlanningErrorCode",
    "ZerodhaPlannedRequest",
    "ZerodhaPlanningError",
    "ZerodhaPlanningInput",
    "plan_historical_candles",
]
